### ISSUE TITLE
'Positive' aspect of level variable in netCDF files via gritas.x is always 'down', regardless of observing system

### ISSUE THREAD

**Issue by CEgerer93** [GEOS-ESM/GrITAS#10]
The `vertical units` of an instrument belonging to an observing system can be toggled between `hPa` (pressure levels) and `index` (channel numbers) without the users knowledge (e.g., when forming yaml to control plotting), provided the variable `variables.lev` within any netCDF file has its `positive` aspect set correctly. The correctness of `positive` is based on line 1961 of `Shared/@GMAO_Shared/GMAO_etc/lats4d.gs`

Regardless of whether a conventional observation or satellite-based observation is considered, the `positive` aspect is always `down`.

Line 525 of `Shared/@GMAO_Shared/GMAO_gfio/gfio.f` seems to the culprit.

**Comment by rtodling** [comment]
Colin, I am confused: why is this an issue?

**Comment by CEgerer93** [comment]
No longer an issue.

The change in your open PR #11 achieves the 'hPa'/'1' distinction I was eluding to with this issue. Having this distinction will allow for descending/ascending vertical axes. This issue should close when #11 is merged - I will close it manually if it doesn't.

**Comment by rtodling** [comment]
ok closing now.
