### ISSUE TITLE
A few suggestions in the plotting

### ISSUE THREAD

**Issue by rtodling** [GEOS-ESM/GrITAS#5]
These are some suggestions for improved readability of the plots:

1) increased font in the y- and x-axis - the font size on the y-axis will need to depend on the number of levels being displayed - in the case of channel numbers (which is the only cases being exercised so far), all channels should show in the y-axis (which is presently the case; which implies that, if the font size will be flexible, it would have to be small when instruments such as IASI, AIRS and CrIS are handled - w hundreds of channels; but in other cases, the fantasize can be a nice readable size.

2) when displaying only mean and/or standard deviations, ie when not doing a cross experiment comparison, it would be nice to have the option of making a line plot as opposed to a bar plot as it is the default now.

3) in the ratio comparison plots, it would be nice to add the mean comparison plots in the same fig - line in the fig attached here ...
<img width="679" alt="Untitled" src="https://github.com/GEOS-ESM/GrITAS/assets/14125601/54ca2277-33fa-4250-ac36-b670ec9a4dd0">
The red curves refer to the standard deviation ratio, the black curve to the mean differences; the bottom x-axis is for the stddev ratio; the top x-axis for the mean-diff.

**Comment by CEgerer93** [comment]
Thanks @rtodling for the suggestions. I will get to work on these.
The first and second points will be easy to address. For the third point, I'll add an option that allows the user to toggle between combining the ratio/difference comparisons into one figure or show them separately.
